context:
  name: s3manager 
  version: "0.5.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/cloudlena/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 97da3dd54f2e7275a48418d416b60befd663d3316435f2e66149278070568995
    target_directory: src

build:
  number: 0
  script:
    - cd src
    - go-licenses save ./ --save_path ../library_licenses --ignore github.com/cloudlena/s3manager
    - if: win
      then: go build -v -buildmode=pie -trimpath -modcacherw -o %LIBRARY_BIN%\s3manager.exe -ldflags="-s" ./main.go
      else: go build -v -buildmode=pie -trimpath -modcacherw -o $PREFIX/bin/s3manager -ldflags="-s -w" ./main.go

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - if: win
        then: 
          - s3manager.exe > output.txt 2>&1
          - findstr /c:"please provide ACCESS_KEY_ID" output.txt
        else: s3manager 2>&1 | grep -q "please provide ACCESS_KEY_ID"

about:
  homepage: https://github.com/cloudlena/s3manager
  summary: A Web GUI for your S3 buckets 
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  repository: https://github.com/cloudlena/s3manager

extra:
  recipe-maintainers:
    - delsner
    - janjagusch
